name: sdrpp
base: core24
version: '1.2.1'
summary: SDRPlusPlus
description: |
  SDR++ is a cross-platform and open source SDR software with the aim of being bloat free and simple to use.

platforms:
  amd64:
grade: stable
confinement: strict

layout:
  /usr/bin/sdrpp:
    bind-file: $SNAP/usr/bin/sdrpp
  /usr/share/sdrpp:
    bind: $SNAP/usr/share/sdrpp
  /usr/lib/sdrpp/plugins:
    bind: $SNAP/usr/lib/sdrpp/plugins
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa


apps:
  sdrpp:
    command: usr/bin/sdrpp
    plugs:
      - network
      - network-bind
      - opengl
      - audio-playback
      - audio-record
      - jack1
      - pulseaudio
      - home
      - alsa
      - desktop
    environment:
      # pulseaudio
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio

parts:
  sdrpp-deb:
    plugin: dump
    source: https://github.com/AlexandreRouma/SDRPlusPlus/releases/download/nightly/sdrpp_ubuntu_noble_amd64.deb
    source-type: deb
    stage-packages:
      - libopengl-dev
      - libfftw3-dev
      - libglfw3-dev
      - libvolk-dev
      - libairspy-dev
      - libbladerf-dev
      - libhackrf-dev
      - libzstd-dev
      - libsoapysdr-dev
      - libairspyhf-dev
      - libiio-dev
      - libad9361-dev
      - librtaudio-dev
      - libglu1-mesa
      - rtl-sdr
      - pulseaudio
      - libpulse-dev
      - libasound2
      - libasound2-plugins